Car Dealership/GuildCars.UI/Models/PurchaseViewModel.cs
using GuildCars.Models.Queries;
using GuildCars.Models.Tables;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;

namespace GuildCars.UI.Models
{
    public class PurchaseViewModel: IValidatableObject
    {
        public VehicleDetailItem Vehicle { get; set; }
        public IEnumerable<State> States { get; set; }
        public IEnumerable<PurchaseType> PurchaseType { get; set; }
        public Purchase Purchase { get; set; }

        public static bool IsPhoneNumber(string Phone)
        {
            if (Regex.Match(Phone, @"1?[\s.-]?\(?(\d{3})\)?[\s.-]?\d{3}[\s.-]?\d{4}").Success)
            {
                return true;
            }

            return false;
        }

        public static bool IsEmail(string Email)
        {
            if (Regex.Match(Email, @"(.*)@(.*)\.(.*)").Success)
            {
                return true;
            }

            return false;
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            List<ValidationResult> errors = new List<ValidationResult>();

            if (string.IsNullOrEmpty(Purchase.Email) && (string.IsNullOrEmpty(Purchase.Phone)))
            {
                errors.Add(new ValidationResult("A Phone number or Email address must be provided."));
            }

            bool validPhoneNumber = false;
            bool validEmail = false;

            if (!string.IsNullOrEmpty(Purchase.Phone))
            {
                validPhoneNumber = IsPhoneNumber(Purchase.Phone);
            }

            if (!string.IsNullOrEmpty(Purchase.Email))
            {
                validEmail = IsEmail(Purchase.Email);
            }

            if (!validPhoneNumber)
            {
                errors.Add(new ValidationResult("Please enter a valid phone number."));
            }

            if (!validEmail)
            {
                errors.Add(new ValidationResult("Please enter a valid Email."));
            }

            if (!validPhoneNumber && string.IsNullOrEmpty(Purchase.Email))
            {
                errors.Add(new ValidationResult("Please enter a valid phone number or put in an email address."));
            }

            if (!validEmail && string.IsNullOrEmpty(Purchase.Phone))
            {
                errors.Add(new ValidationResult("Please enter a valid Email or put in a phone number."));
            }

            if (string.IsNullOrEmpty(Purchase.PurchaseName))
            {
                errors.Add(new ValidationResult("Please enter a valid Name for purchase."));
            }

            if (string.IsNullOrEmpty(Purchase.Street1))
            {
                errors.Add(new ValidationResult("Please enter a valid street address for purchase."));
            }

            if (string.IsNullOrEmpty(Purchase.City))
            {
                errors.Add(new ValidationResult("Please enter a valid City for purchase."));
            }

            if (Purchase.Zipcode <= 9999.99m)
            {
                errors.Add(new ValidationResult("Please enter a valid Zipcode for purchase."));
            }

            if (Purchase.PurchasePrice < Vehicle.Price - (Vehicle.Price * 5 / 100))
            {
                errors.Add(new ValidationResult("The purchase price cannot be less than 95% of the advertised price."));
            }

            if (Purchase.PurchasePrice > Vehicle.MSRP)
            {
                errors.Add(new ValidationResult("The purchase price cannot be larger than the MSRP."));
            }

            return errors;
        }
    }
}

Car Dealership/GuildCars.UI/Controllers/SalesController.cs
using GuildCars.Data.Factories;
using GuildCars.Models.Tables;
using GuildCars.UI.Models;
using GuildCars.UI.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GuildCars.UI.Controllers
{
    public class SalesController : Controller
    {
        [Authorize(Roles = "admin,sales")]
        public ActionResult Index()
        {
            var model = Utilities.InventorySearchUtilities.searchModelValues();

            return View(model);
        }

        [Authorize(Roles = "admin,sales")]
        public ActionResult Purchase(string vinNumber)
        {
            var vehicleRepo = VehiclesRepositoryFactory.GetRepository();
            var stateRepo = StatesRepositoryFactory.GetRepository();
            var purchaseTypeRepo = PurchaseTypesRepositoryFactory.GetRepository();

            var model = new PurchaseViewModel();

            model.Vehicle = vehicleRepo.GetDetails(vinNumber);
            model.States = stateRepo.GetAll();
            model.PurchaseType = purchaseTypeRepo.GetAll();

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "admin,sales")]
        public ActionResult Purchase(PurchaseViewModel model)
        {
            if (ModelState.IsValid)
            {
                var repo = PurchasesRepositoryFactory.GetRepository();

                model.Purchase.VehicleId = model.Vehicle.VehicleId;

                model.Purchase.UserId = AuthorizeUtilities.GetUserId(this);

                model.Purchase.PurchaseDate = DateTime.UtcNow;

                repo.AddPurchase(model.Purchase);

                return RedirectToAction("Index", "sales");
            }
            else
            {
                var vehicleRepo = VehiclesRepositoryFactory.GetRepository();
                var stateRepo = StatesRepositoryFactory.GetRepository();
                var purchaseTypeRepo = PurchaseTypesRepositoryFactory.GetRepository();

                var purchaseModel = new PurchaseViewModel();

                purchaseModel.Vehicle = vehicleRepo.GetDetails(model.Vehicle.VinNumber);
                purchaseModel.States = stateRepo.GetAll();
                purchaseModel.PurchaseType = purchaseTypeRepo.GetAll();

                return View(purchaseModel);
            }
        }
    }
}

Car Dealership/GuildCars.UI/Views/Sales/Index.cshtml
@model GuildCars.UI.Models.SearchFieldsModel

@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="col-xs-12">
        <h3>Sales</h3>
    </div>
</div>
<div class="row">
    <div class="col-xs-12">
        <label for="quickSearch">Quick Search</label>
        <form id="allSearchForm" class="form-inline">
            <div class="col-xs-12">
                <div class="form-group col-xs-4">
                    <input type="text" placeholder="Enter make, model or year" class="form-control" id="quickSearch" />
                </div>
                <div class="form-group col-xs-4">
                    <label for="minPrice maxPrice">Price</label>
                    @Html.DropDownList("minPrice", new SelectList(Model.MinPriceDropdownValue), "No Min", new { @class = "form-control" })
                    @Html.DropDownList("maxPrice", new SelectList(Model.MaxPriceDropdownValue), "No Max", new { @class = "form-control" })
                </div>
                <div class="form-group col-xs-4">
                    <label for="minYear maxYear">Year</label>
                    @Html.DropDownList("minYear", new SelectList(Model.YearDropDownValue), "No Min", new { @class = "form-control" })
                    @Html.DropDownList("maxYear", new SelectList(Model.YearDropDownValue), "No Max", new { @class = "form-control" })
                </div>
            </div>
            <button id="btnSearch" class="btn btn-default">Search</button>
        </form>
    </div>
</div>
<br />
<div class="row" id="searchResults">

</div>

@section Scripts
{
    <script>
        $(document).ready(function () {
            $("#allSearchForm").submit(function (e) {
                search();
                return false;
            });
        });

        function search() {
            var params;
            var imagePath = '@Url.Content("~/Images/")';
            var editPath = '@Url.Action("Purchase", "Sales")?';

            params = 'quickSearch=' + $('#quickSearch').val() +
                      '&minPrice=' + $('#minPrice').val() + '&maxPrice=' + $('#maxPrice').val() +
                       '&minYear=' + $('#minYear').val() + '&maxYear=' + $('#maxYear').val();

            $.ajax({
                type: 'GET',
                url: 'http://localhost:52489/sales/vehicle/search?' + params,
                success: function (results) {
                    $('#searchResults').empty();

                    $.each(results, function (index, vehicle) {
                        if (vehicle.Milage < 1000) {
                            vehicle.Milage = "New";
                        }

                        var html ='<div class="col-xs-12">' +
                                       '<div class="col-md-12">' +
                                            '<p>' + vehicle.VehicleYear + " " + vehicle.MakeName + " " + vehicle.ModelName + '</p>' +
                                       '</div>' +
                                       '<div class="col-xs-12 col-sm-4 col-md-3" id="DetailsImage">' +
                                           '<img src="' + imagePath + vehicle.ImageFileName + '"/>' +
                                       '</div>' +
                                       '<div class="col-xs-12 col-sm-4 col-md-3">' +
                                           '<table>' +
                                               '<tbody>' +
                                                   '<tr>' +
                                                       '<td style="text-align: right"><strong>Body Style:</strong></td>' +
                                                       '<td> ' + vehicle.BodyStyleName + '</td>' +
                                                   '</tr>' +
                                                   '<tr>' +
                                                       '<td style="text-align: right"><strong>Trans:</strong></td>' +
                                                       '<td> ' + vehicle.TransmissionName + '</td>' +
                                                   '</tr>' +
                                                   '<tr>' +
                                                       '<td style="text-align: right"><strong>Color:</strong></td> ' +
                                                       '<td> ' + vehicle.ExteriorColorName + '</td>' +
                                                   '</tr>' +
                                               '</tbody>' +
                                           '</table>' +
                                       '</div>' +
                                       '<div class="col-xs-12 col-sm-4 col-md-3">' +
                                           '<table>' +
                                               '<tbody>' +
                                                   '<tr>' +
                                                       '<td style="text-align: right"><strong>Interior:</strong></td>' +
                                                       '<td> ' + vehicle.InteriorName + '</td>' +
                                                   '</tr>' +
                                                   '<tr>' +
                                                       '<td style="text-align: right"><strong>Milage:</strong></td>' +
                                                       '<td>' + vehicle.Milage + '</td>' +
                                                   '</tr>' +
                                                   '<tr>' +
                                                       '<td style="text-align: right"><strong>VIN #:</strong></td>' +
                                                       '<td> ' + vehicle.VinNumber + '</td>' +
                                                   '</tr>' +
                                               '</tbody>' +
                                           '</table>' +
                                       '</div>' +
                                       '<div class="col-xs-12 col-sm-4 col-md-3">' +
                                           '<table>' +
                                               '<tbody>' +
                                                   '<tr>' +
                                                       '<td style="text-align: right"><strong>Sale Price:</strong></td>' +
                                                       '<td> ' + '$' + vehicle.Price + '</td>' +
                                                   '</tr>' +
                                                   '<tr>' +
                                                       '<td style="text-align: right"><strong>MSRP:</strong></td>' +
                                                       '<td> ' + '$' + vehicle.MSRP + '</td>' +
                                                   '</tr>' +
                                                        '<td>  ' +
                                                        '</td>' +
                                                   '<tr>' +
                                                   '</tr>' +
                                                   '<tr>' +
                                                       '<td><button class="btn btn-default"><a href="' + editPath + "vinNumber=" + vehicle.VinNumber + '">Purchase</a></button></td>' +
                                                   '</tr>' +
                                               '</tbody>' +
                                           '</table>' +
                                       '</div>' +
                                '</div>' +
                                '<hr>';

                        $('#searchResults').append(html.toString());
                    });
                },
                error: function () {
                    alert('Error performing search, try again later!')
                }
            });
        }
    </script>
}

Car Dealership/GuildCars.UI/Views/Sales/Purchase.cshtml
@model GuildCars.UI.Models.PurchaseViewModel

@{
    ViewBag.Title = "Purchase";
}

<div class="row">
    <div class="col-xs-12">
        <h3>Purchase Vehicle</h3>
    </div>
</div>
<div class="row">
    <div class="col-xs-12">
        <p>@Model.Vehicle.VehicleYear @Model.Vehicle.MakeName @Model.Vehicle.ModelName</p>
    </div>
    <div class="col-xs-12 col-sm-4 col-md-3" id="DetailsImage">
        <img src="@Url.Content("~/Images/" + Model.Vehicle.ImageFileName)" />
    </div>
    <div class="col-xs-12 col-sm-4 col-md-3">
        <table>
            <tbody>
                <tr>
                    <td style="text-align: right"><strong>Body Style:</strong></td>
                    <td>@Model.Vehicle.BodyStyleName</td>
                </tr>
                <tr>
                    <td style="text-align: right"><strong>Trans:</strong></td>
                    <td>@Model.Vehicle.TransmissionName</td>
                </tr>
                <tr>
                    <td style="text-align: right"><strong>Color:</strong></td>
                    <td>@Model.Vehicle.ExteriorColorName</td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="col-xs-12 col-sm-4 col-md-3">
        <table>
            <tbody>
                <tr>
                    <td style="text-align: right"><strong>Interior:</strong></td>
                    <td>@Model.Vehicle.InteriorName</td>
                </tr>
                <tr>
                    <td style="text-align: right"><strong>Milage:</strong></td>
                    <td>@Model.Vehicle.Milage</td>
                </tr>
                <tr>
                    <td style="text-align: right"><strong>VIN #:</strong></td>
                    <td>@Model.Vehicle.VinNumber</td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="col-xs-12 col-sm-4 col-md-3">
        <table>
            <tbody>
                <tr>
                    <td style="text-align: right"><strong>Sale Price:</strong></td>
                    <td>@Model.Vehicle.Price.ToString("c")</td>
                </tr>
                <tr>
                    <td style="text-align: right"><strong>MSRP:</strong></td>
                    <td>@Model.Vehicle.MSRP.ToString("c")</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
<div class="row">
    <div class="col-xs-3">
    </div>
    <div class="col-xs-9">
        <table>
            <tbody>
                <tr>
                    <td style="text-align: right"><strong>Description:</strong></td>
                    <td>@Model.Vehicle.ListingDescription</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
<br />
<div class="row">
    <div class="col-xs-12">
        <h3>Sale Information</h3>
    </div>
</div>
@using (Html.BeginForm("Purchase", "Sales", FormMethod.Post, new { @class = "form-horizontal", role = "form", id = "frmPurchaseVehicle"}))
{
    @Html.ValidationSummary()
    @Html.Hidden("Vehicle.VehicleId", Model.Vehicle.VehicleId)
    @Html.Hidden("Vehicle.vinNumber", Model.Vehicle.VinNumber)
    @Html.Hidden("Vehicle.msrp", Model.Vehicle.MSRP)
    @Html.Hidden("Vehicle.price", Model.Vehicle.Price)
    <div class="col-xs-12">
        <form>
            <div class="col-md-12">
                <div class="form-group col-md-6">
                    @Html.LabelFor(m => m.Purchase.PurchaseName, "Name", new { @class = "control-label" })
                    @Html.TextBoxFor(m => m.Purchase.PurchaseName, new { @class = "form-control" })
                </div>
                <div class="form-group col-md-6">
                    @Html.LabelFor(m => m.Purchase.Phone, new { @class = "control-label" })
                    @Html.TextBoxFor(m => m.Purchase.Phone, new { @class = "form-control" , @id = "PurchasePhone"})
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group col-md-6">
                    @Html.LabelFor(m => m.Purchase.Email, new { @class = "control-label" })
                    @Html.TextBoxFor(m => m.Purchase.Email, new { @class = "form-control", @id = "PurchaseEmail" })
                </div>                
            </div>
            <div class="col-md-12">
                <div class="form-group col-md-6">
                    @Html.LabelFor(m => m.Purchase.Street1, "Street 1", new { @class = "control-label" })
                    @Html.TextBoxFor(m => m.Purchase.Street1, new { @class = "form-control" })
                </div>
                <div class="form-group col-md-6">
                    @Html.LabelFor(m => m.Purchase.Street2, "Street 1", new { @class = "control-label" })
                    @Html.TextBoxFor(m => m.Purchase.Street2, new { @class = "form-control" })
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group col-md-6">
                    @Html.LabelFor(m => m.Purchase.City, new { @class = "control-label" })
                    @Html.TextBoxFor(m => m.Purchase.City, new { @class = "form-control" })
                </div>
                <div class="form-group col-md-6">
                    @Html.LabelFor(m => m.States, "Type", new { @class = "control-label" })
                    @Html.DropDownList("purchase.StateId", new SelectList(Model.States, "StateId", "StateId"), new { @class = "form-control" })
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group col-md-6">
                    @Html.LabelFor(m => m.Purchase.Zipcode, new { @class = "control-label" })
                    @Html.TextBoxFor(m => m.Purchase.Zipcode, new { @class = "form-control" })
                </div>
            </div>
            <hr style="width: 100%"/>
            <div class="col-md-12">
                <div class="form-group col-md-6">
                    @Html.LabelFor(m => m.Purchase.PurchasePrice, "Purchase Price", new { @class = "control-label" })
                    @Html.TextBoxFor(m => m.Purchase.PurchasePrice, new { @class = "form-control" })
                </div>
                <div class="form-group col-md-6">
                    @Html.LabelFor(m => m.PurchaseType, "Purchase Type", new { @class = "control-label" })
                    @Html.DropDownList("purchase.PurchaseTypeId", new SelectList(Model.PurchaseType, "PurchaseTypeId", "PurchaseTypeName"), new { @class = "form-control" })
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group col-xs-12">
                    <button class="btn btn-default">Save</button>
                </div>
            </div>
        </form>
    </div>
}

@section scripts
{
    <script>
        $(document).ready(function () {

            $('#frmPurchaseVehicle').validate({
                rules: {
                    'Purchase.PurchaseName': {
                        required: true
                    },
                    'Purchase.Phone': {
                        required: function () {
                            if ($('#PurchaseEmail').val() == "")
                                return true;
                            else
                                return false;
                        }
                    },
                    'Purchase.Email': {
                        required: function () {
                            if ($('#PurchasePhone').val() == "")
                                return true;
                            else
                                return false;
                        }
                    },
                    'Purchase.Street1': {
                        required: true
                    },
                    'Purchase.City': {
                        required: true
                    },
                    'States': {
                        required: true
                    },
                    'Purchase.Zipcode': {
                        required: true,
                        number: true,
                        minlength: 5,
                        maxlength: 5
                    },
                    'Purchase.PurchasePrice': {
                        required: true,
                        number: true,
                        min: 1
                    },
                    'PurchaseType': {
                        required: true,
                    }
                }
            });

        });
    </script>
}