Car Dealership/GuildCars.UI/Controllers/InventoryController.cs
using GuildCars.Data.Factories;
using GuildCars.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GuildCars.UI.Controllers
{
    public class InventoryController : Controller
    {
        

        // GET: Inventory
        public ActionResult Details(string vinNumber)
        {
            var vehichleRepo = VehiclesRepositoryFactory.GetRepository();
            var vehichleModel = vehichleRepo.GetDetails(vinNumber);

            return View(vehichleModel);
        }
        
        public ActionResult New()
        {
            var model = Utilities.InventorySearchUtilities.searchModelValues();

            return View(model);
        }

        public ActionResult Used()
        {
            var model = Utilities.InventorySearchUtilities.searchModelValues();

            return View(model);
        }

    }
}

Car Dealership/GuildCars.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>                               
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li id="logoImage"><img src=@Url.Content("~/Images/logo.png") /></li>
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("New Inventory", "New", "Inventory")</li>
                    <li>@Html.ActionLink("Used Inventory", "Used", "Inventory")</li>
                    <li>@Html.ActionLink("Specials", "Special", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    @Html.Partial("_LoginPartial")
                </ul>                
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>